import mongoose from 'mongoose';

const purchaseReturnItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  productName: String,
  batch: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Batch'
    // Optional for backwards compatibility
  },
  batchNo: String,
  expiryDate: Date,
  hsnCode: String,
  quantity: {
    type: Number,
    required: true
  },
  unit: String,
  purchasePrice: {
    type: Number,
    required: true
  },
  gstRate: {
    type: Number,
    required: true
  },
  taxableAmount: Number,
  cgst: Number,
  sgst: Number,
  igst: Number,
  totalAmount: Number
});

const purchaseReturnSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  debitNoteNumber: {
    type: String,
    unique: true
    // Auto-generated by pre-save hook
  },
  supplier: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Supplier',
    required: true
  },
  supplierName: String,
  supplierGstin: String,
  // Reference to original purchase
  originalPurchase: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Purchase',
    required: true
  },
  originalPurchaseNumber: String,
  returnDate: {
    type: Date,
    default: Date.now,
    required: true
  },
  reason: {
    type: String,
    enum: ['DAMAGED', 'EXPIRED', 'WRONG_ITEM', 'QUALITY_ISSUE', 'EXCESS_STOCK', 'OTHER'],
    required: true
  },
  reasonDescription: String,
  items: [purchaseReturnItemSchema],
  taxType: {
    type: String,
    enum: ['CGST_SGST', 'IGST'],
    required: true
  },
  subtotal: {
    type: Number,
    required: true
  },
  totalTax: {
    type: Number,
    required: true
  },
  totalCGST: {
    type: Number,
    default: 0
  },
  totalSGST: {
    type: Number,
    default: 0
  },
  totalIGST: {
    type: Number,
    default: 0
  },
  roundOff: {
    type: Number,
    default: 0
  },
  grandTotal: {
    type: Number,
    required: true
  },
  adjustmentStatus: {
    type: String,
    enum: ['PENDING', 'ADJUSTED', 'REFUNDED'],
    default: 'PENDING'
  },
  adjustmentMethod: {
    type: String,
    enum: ['CREDIT_NOTE', 'CASH_REFUND', 'BANK_TRANSFER', 'ADJUST_NEXT_BILL']
  },
  notes: String,
  // For accounting
  ledgerEntries: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ledger'
  }]
}, {
  timestamps: true
});

// Auto-increment debit note number
purchaseReturnSchema.pre('save', async function(next) {
  if (this.isNew) {
    const lastReturn = await this.constructor.findOne({ userId: this.userId })
      .sort({ createdAt: -1 });

    let nextNumber = 1;
    if (lastReturn && lastReturn.debitNoteNumber) {
      const lastNumber = parseInt(lastReturn.debitNoteNumber.split('-').pop());
      nextNumber = lastNumber + 1;
    }

    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    this.debitNoteNumber = `DN-${year}${month}-${String(nextNumber).padStart(4, '0')}`;
  }
  next();
});

const PurchaseReturn = mongoose.model('PurchaseReturn', purchaseReturnSchema);
export default PurchaseReturn;
