import mongoose from 'mongoose';

const purchaseItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  productName: String,
  batchNo: {
    type: String,
    required: true
  },
  expiryDate: {
    type: Date,
    required: true
  },
  manufacturingDate: {
    type: Date
  },
  hsnCode: String,
  quantity: {
    type: Number,
    required: true
  },
  freeQuantity: {
    type: Number,
    default: 0
  },
  unit: String,
  mrp: {
    type: Number,
    required: true
  },
  purchasePrice: {
    type: Number,
    required: true
  },
  sellingPrice: {
    type: Number,
    required: true
  },
  gstRate: {
    type: Number,
    required: true
  },
  discount: {
    type: Number,
    default: 0
  },
  discountAmount: {
    type: Number,
    default: 0
  },
  taxableAmount: Number,
  cgst: Number,
  sgst: Number,
  igst: Number,
  totalAmount: Number,
  // Link to created batch
  batch: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Batch'
  }
});

const purchaseSchema = new mongoose.Schema({
  organizationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: true,
    index: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  purchaseNumber: {
    type: String,
    unique: true
    // Auto-generated by pre-save hook
  },
  supplier: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Supplier',
    required: true
  },
  supplierName: String,
  supplierGstin: String,
  supplierInvoiceNo: {
    type: String
  },
  supplierInvoiceDate: {
    type: Date
  },
  purchaseDate: {
    type: Date,
    default: Date.now,
    required: true
  },
  dueDate: {
    type: Date
  },
  items: [purchaseItemSchema],
  // Tax type based on supplier state
  taxType: {
    type: String,
    enum: ['CGST_SGST', 'IGST'],
    required: true
  },
  subtotal: {
    type: Number,
    required: true
  },
  totalTax: {
    type: Number,
    required: true
  },
  totalCGST: {
    type: Number,
    default: 0
  },
  totalSGST: {
    type: Number,
    default: 0
  },
  totalIGST: {
    type: Number,
    default: 0
  },
  discount: {
    type: Number,
    default: 0
  },
  // Additional charges
  freight: {
    type: Number,
    default: 0
  },
  packaging: {
    type: Number,
    default: 0
  },
  otherCharges: {
    type: Number,
    default: 0
  },
  roundOff: {
    type: Number,
    default: 0
  },
  grandTotal: {
    type: Number,
    required: true
  },
  paymentStatus: {
    type: String,
    enum: ['PAID', 'UNPAID', 'PARTIAL'],
    default: 'UNPAID'
  },
  paymentMethod: {
    type: String,
    enum: ['CASH', 'CHEQUE', 'BANK_TRANSFER', 'CREDIT'],
    default: 'CREDIT'
  },
  paidAmount: {
    type: Number,
    default: 0
  },
  balanceAmount: {
    type: Number,
    default: 0
  },
  paymentTerms: String,
  notes: String,
  // For returns
  isReturned: {
    type: Boolean,
    default: false
  },
  returnedAmount: {
    type: Number,
    default: 0
  },
  // For accounting
  ledgerEntries: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ledger'
  }]
}, {
  timestamps: true
});

// Indexes for multi-tenant queries
purchaseSchema.index({ organizationId: 1, purchaseDate: -1 });
purchaseSchema.index({ organizationId: 1, supplier: 1 });
purchaseSchema.index({ organizationId: 1, paymentStatus: 1 });

// Auto-increment purchase number (per organization)
purchaseSchema.pre('save', async function (next) {
  if (this.isNew) {
    const lastPurchase = await this.constructor.findOne({
      organizationId: this.organizationId
    }).sort({ createdAt: -1 });

    let nextNumber = 1;
    if (lastPurchase && lastPurchase.purchaseNumber) {
      const lastNumber = parseInt(lastPurchase.purchaseNumber.split('-').pop());
      nextNumber = lastNumber + 1;
    }

    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    this.purchaseNumber = `PUR-${year}${month}-${String(nextNumber).padStart(4, '0')}`;
  }
  next();
});

const Purchase = mongoose.model('Purchase', purchaseSchema);
export default Purchase;
